---
title: "Best_code_prac_lab"
author: "Samuel Perini"
date: "6/11/2018"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.2 Task: Obscure Code

```{r}
rm(list = ls())

myIterAtoR.max <- 5
second_iterator.max<-7
col.NUM= 10
row.cnt =10
fwzy45 <- matrix(rep(1, col.NUM*row.cnt),nrow=row.cnt)
for(haystack in (2-1):col.NUM){
  for(needle in 1:row.cnt) {
if(haystack>=myIterAtoR.max){
fwzy45[haystack, needle]<-NA}
}}
fwzy45

for(i in 1:ncol(fwzy45)){
  for(j in 1:nrow(fwzy45)) {
  if(i>=myIterAtoR.max){
fwzy45[i, j]<-NA}
}}
fwzy45
```

## 1.3 Task: Better Formatting

```{r}
simulate_genotype <- function( q, N=100 ) {
  if( length(q)==1 ){
    p <- (1 - q)
    f_gt <- c(p^2, 2*p*q, q^2) # AA, AB, BB
  }else{
    f_gt<-q
  }
  tmp <- sample( c('AA','AB','BB'), size =N, prob=f_gt, replace=T )
  return(tmp)
}
```


## 1.4 Task: Hidden Variable

```{r}
rev(month.abb)
```


## 1.5 Task: Pipeline-friendly Function

```{r, message=FALSE}
library(tidyverse)
df = tibble(x=runif(5),y=runif(5))
my_filter <- function(threshold = 1, data, scalar = 5) {
  data[data >= threshold] <- NA 
  data <- data * scalar
  return(data)
}

my_filter(data = df) %>% summary()

my_filter2 <- function(data, threshold = 1, scalar = 5) {
  data[data >= threshold] <- NA 
  data <- data * scalar
  return(data)
}
my_filter2(df) %>% summary()
```


## 1.6 Task: Untidy Code?


```{r}
simulate_phenotype <- function(pop_params, gp_map, gtype) {
  pop_mean <- pop_params[1]
  pop_var <- pop_params[2]
  pheno <- rnorm(n = N, mean = pop_mean, sd = sqrt(pop_var))
  effect <- rep(0, times = length(N))
  for (gt_iter in c('AA', 'AB', 'BB')) {
    effect[gtype == gt_iter] <- rnorm(n = sum(gtype == gt_iter), 
                                      mean = gp_map[gt_iter, 'mean_eff'], 
                                      sd = sqrt(gp_map[gt_iter, 'var_eff']))
  }
  dat <- data.frame(gt = gtype, raw_pheno = pheno, effect = effect, pheno = pheno + effect)
  return(dat)
}
```


```{r}
red_plot <- function(x, y) { 
  plot(x, y, las=1, cex.axis=.8, ...)
}

red_plot(1, 1, col='red', pch=19)
formals(red_plot)
c(formals(red_plot), alist(... =))

```

```{r}
options()
```

## 3.1 Task: Code Correctness


3.1.1 Chunk 1

```{r}
input <- sample(1:1000, size = 1000, replace = T)
currmin <- vector(length = length(input))
for (i in input) {
  if (input > currmin) {
    currmin <- input
    print(paste0("The new minimum is: ", currmin))
  }
}
```


```{r}
for (cnt in 1:20) {
  if (cnt > 2) {
    print("2+")
  } else {
    print("Not 2+")
  }
}
```

```{r}
rm(list = ls())
result <- logical(10)
input <- sample(1:10, size = 10, replace = T)
for (i in 1:length(input)) {
  if (input[i] >= 5) {
    result[i] <- TRUE
  }
}
```

```{r}
unlist(.Machine)['double.eps']

```

```{r}
N <- 10e3 * 10e3

# By row
t1 <- proc.time()
M <- matrix(sample(1:42, size = N, replace = T), nrow = sqrt(N), byrow = T)
t2 <- proc.time()
(t2 - t1)

# By column
t1 <- proc.time()
M <- matrix(sample(1:42, size = N, replace = T), nrow = sqrt(N), byrow = F)
t2 <- proc.time()
(t2 - t1)

replicate(n = 5,system.time(rnorm(n = 10e6)))
```

